name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código-fonte
        uses: actions/checkout@v2

      - name: Build da imagem Docker
        run: docker-compose build

      - name: Homologação
        run: docker-compose up -d && docker-compose exec python pytest && docker-compose down

      - name: Implantação
        run: docker-compose up -d