version: '3'

services:
  db:
    image: mydb
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - .env
    networks:
      - pywork

  python:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - sua_rpyworkede_docker
    command: python -u main.py

networks:
  pywork:
    driver: bridge
